version: "3.1"

services:
  db:
    image: postgres
    container_name: PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: sokoban
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - sokoban:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sokoban:
