name: Check
on:
  push:
    branches:
      - dev
      - prod
  pull_request:
jobs:
  check:
    name: Checker
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout
        uses: actions/checkout@v3

      - name: Set up environment
        uses: ./.github/actions/environment

      - name: Check Back-end code style
        uses: ./.github/actions/backend-code-style
